name: Generate Snake Animation

on:
  # Esegue ogni 12 ore
  schedule:
    - cron: "0 */12 * * *"
  
  # Permette l'esecuzione manuale
  workflow_dispatch:
  
  # Esegue ad ogni push sul branch main
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Genera l'animazione del serpente
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: rbrtsl
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # Pubblica l'animazione sul branch output
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
